/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IBattleArena {
  export type BattleStruct = {
    challenger: AddressLike;
    createdAt: BigNumberish;
    status: BigNumberish;
    opponent: AddressLike;
    completedAt: BigNumberish;
    challengerCardId: BigNumberish;
    winner: AddressLike;
    opponentCardId: BigNumberish;
    battleId: BigNumberish;
  };

  export type BattleStructOutput = [
    challenger: string,
    createdAt: bigint,
    status: bigint,
    opponent: string,
    completedAt: bigint,
    challengerCardId: bigint,
    winner: string,
    opponentCardId: bigint,
    battleId: bigint
  ] & {
    challenger: string;
    createdAt: bigint;
    status: bigint;
    opponent: string;
    completedAt: bigint;
    challengerCardId: bigint;
    winner: string;
    opponentCardId: bigint;
    battleId: bigint;
  };

  export type PlayerStatsStruct = {
    wins: BigNumberish;
    losses: BigNumberish;
    totalBattles: BigNumberish;
    currentStreak: BigNumberish;
    bestStreak: BigNumberish;
  };

  export type PlayerStatsStructOutput = [
    wins: bigint,
    losses: bigint,
    totalBattles: bigint,
    currentStreak: bigint,
    bestStreak: bigint
  ] & {
    wins: bigint;
    losses: bigint;
    totalBattles: bigint;
    currentStreak: bigint;
    bestStreak: bigint;
  };
}

export interface BattleArenaInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "MAX_LEADERBOARD_SIZE"
      | "REWARDS_ROLE"
      | "acceptChallenge"
      | "activeChallenges"
      | "battles"
      | "cancelChallenge"
      | "cardContract"
      | "challengeTimeout"
      | "createChallenge"
      | "getBattle"
      | "getLeaderboard"
      | "getPlayerActiveChallenges"
      | "getPlayerPendingChallenges"
      | "getPlayerStats"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "leaderboardAddresses"
      | "leaderboardPosition"
      | "loserExpReward"
      | "pause"
      | "paused"
      | "pendingChallenges"
      | "playerStats"
      | "renounceRole"
      | "revokeRole"
      | "setChallengeTimeout"
      | "setExpRewards"
      | "supportsInterface"
      | "typeChart"
      | "unpause"
      | "verifySetup"
      | "winnerExpReward"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BattleAccepted"
      | "BattleCancelled"
      | "BattleCompleted"
      | "BattleCreated"
      | "ChallengeTimeoutUpdated"
      | "ExpRewardsUpdated"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_LEADERBOARD_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REWARDS_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptChallenge",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "activeChallenges",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "battles",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelChallenge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cardContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "challengeTimeout",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createChallenge",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBattle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLeaderboard",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerActiveChallenges",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerPendingChallenges",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "leaderboardAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "leaderboardPosition",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "loserExpReward",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingChallenges",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "playerStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setChallengeTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setExpRewards",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "typeChart",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifySetup",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "winnerExpReward",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_LEADERBOARD_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REWARDS_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeChallenges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "battles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cardContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengeTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBattle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLeaderboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerActiveChallenges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerPendingChallenges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "leaderboardAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "leaderboardPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "loserExpReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingChallenges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playerStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setChallengeTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExpRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "typeChart", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifySetup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "winnerExpReward",
    data: BytesLike
  ): Result;
}

export namespace BattleAcceptedEvent {
  export type InputTuple = [
    battleId: BigNumberish,
    opponent: AddressLike,
    opponentCardId: BigNumberish
  ];
  export type OutputTuple = [
    battleId: bigint,
    opponent: string,
    opponentCardId: bigint
  ];
  export interface OutputObject {
    battleId: bigint;
    opponent: string;
    opponentCardId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BattleCancelledEvent {
  export type InputTuple = [battleId: BigNumberish];
  export type OutputTuple = [battleId: bigint];
  export interface OutputObject {
    battleId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BattleCompletedEvent {
  export type InputTuple = [
    battleId: BigNumberish,
    winner: AddressLike,
    winnerCardId: BigNumberish
  ];
  export type OutputTuple = [
    battleId: bigint,
    winner: string,
    winnerCardId: bigint
  ];
  export interface OutputObject {
    battleId: bigint;
    winner: string;
    winnerCardId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BattleCreatedEvent {
  export type InputTuple = [
    battleId: BigNumberish,
    challenger: AddressLike,
    opponent: AddressLike,
    challengerCardId: BigNumberish
  ];
  export type OutputTuple = [
    battleId: bigint,
    challenger: string,
    opponent: string,
    challengerCardId: bigint
  ];
  export interface OutputObject {
    battleId: bigint;
    challenger: string;
    opponent: string;
    challengerCardId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChallengeTimeoutUpdatedEvent {
  export type InputTuple = [oldTimeout: BigNumberish, newTimeout: BigNumberish];
  export type OutputTuple = [oldTimeout: bigint, newTimeout: bigint];
  export interface OutputObject {
    oldTimeout: bigint;
    newTimeout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExpRewardsUpdatedEvent {
  export type InputTuple = [winnerExp: BigNumberish, loserExp: BigNumberish];
  export type OutputTuple = [winnerExp: bigint, loserExp: bigint];
  export interface OutputObject {
    winnerExp: bigint;
    loserExp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BattleArena extends BaseContract {
  connect(runner?: ContractRunner | null): BattleArena;
  waitForDeployment(): Promise<this>;

  interface: BattleArenaInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_LEADERBOARD_SIZE: TypedContractMethod<[], [bigint], "view">;

  REWARDS_ROLE: TypedContractMethod<[], [string], "view">;

  acceptChallenge: TypedContractMethod<
    [battleId: BigNumberish, cardId: BigNumberish],
    [void],
    "nonpayable"
  >;

  activeChallenges: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  battles: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        challenger: string;
        createdAt: bigint;
        status: bigint;
        opponent: string;
        completedAt: bigint;
        challengerCardId: bigint;
        winner: string;
        opponentCardId: bigint;
        battleId: bigint;
      }
    ],
    "view"
  >;

  cancelChallenge: TypedContractMethod<
    [battleId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cardContract: TypedContractMethod<[], [string], "view">;

  challengeTimeout: TypedContractMethod<[], [bigint], "view">;

  createChallenge: TypedContractMethod<
    [opponent: AddressLike, cardId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getBattle: TypedContractMethod<
    [battleId: BigNumberish],
    [IBattleArena.BattleStructOutput],
    "view"
  >;

  getLeaderboard: TypedContractMethod<
    [limit: BigNumberish],
    [[string[], bigint[]] & { addresses: string[]; wins: bigint[] }],
    "view"
  >;

  getPlayerActiveChallenges: TypedContractMethod<
    [player: AddressLike],
    [bigint[]],
    "view"
  >;

  getPlayerPendingChallenges: TypedContractMethod<
    [player: AddressLike],
    [bigint[]],
    "view"
  >;

  getPlayerStats: TypedContractMethod<
    [player: AddressLike],
    [IBattleArena.PlayerStatsStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  leaderboardAddresses: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  leaderboardPosition: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  loserExpReward: TypedContractMethod<[], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingChallenges: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  playerStats: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        wins: bigint;
        losses: bigint;
        totalBattles: bigint;
        currentStreak: bigint;
        bestStreak: bigint;
      }
    ],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setChallengeTimeout: TypedContractMethod<
    [_timeout: BigNumberish],
    [void],
    "nonpayable"
  >;

  setExpRewards: TypedContractMethod<
    [_winnerExp: BigNumberish, _loserExp: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  typeChart: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  verifySetup: TypedContractMethod<[], [boolean], "view">;

  winnerExpReward: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_LEADERBOARD_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REWARDS_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptChallenge"
  ): TypedContractMethod<
    [battleId: BigNumberish, cardId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "activeChallenges"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "battles"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        challenger: string;
        createdAt: bigint;
        status: bigint;
        opponent: string;
        completedAt: bigint;
        challengerCardId: bigint;
        winner: string;
        opponentCardId: bigint;
        battleId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelChallenge"
  ): TypedContractMethod<[battleId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cardContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "challengeTimeout"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createChallenge"
  ): TypedContractMethod<
    [opponent: AddressLike, cardId: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBattle"
  ): TypedContractMethod<
    [battleId: BigNumberish],
    [IBattleArena.BattleStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLeaderboard"
  ): TypedContractMethod<
    [limit: BigNumberish],
    [[string[], bigint[]] & { addresses: string[]; wins: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerActiveChallenges"
  ): TypedContractMethod<[player: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPlayerPendingChallenges"
  ): TypedContractMethod<[player: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPlayerStats"
  ): TypedContractMethod<
    [player: AddressLike],
    [IBattleArena.PlayerStatsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "leaderboardAddresses"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "leaderboardPosition"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "loserExpReward"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingChallenges"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "playerStats"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        wins: bigint;
        losses: bigint;
        totalBattles: bigint;
        currentStreak: bigint;
        bestStreak: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setChallengeTimeout"
  ): TypedContractMethod<[_timeout: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setExpRewards"
  ): TypedContractMethod<
    [_winnerExp: BigNumberish, _loserExp: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "typeChart"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifySetup"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "winnerExpReward"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "BattleAccepted"
  ): TypedContractEvent<
    BattleAcceptedEvent.InputTuple,
    BattleAcceptedEvent.OutputTuple,
    BattleAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "BattleCancelled"
  ): TypedContractEvent<
    BattleCancelledEvent.InputTuple,
    BattleCancelledEvent.OutputTuple,
    BattleCancelledEvent.OutputObject
  >;
  getEvent(
    key: "BattleCompleted"
  ): TypedContractEvent<
    BattleCompletedEvent.InputTuple,
    BattleCompletedEvent.OutputTuple,
    BattleCompletedEvent.OutputObject
  >;
  getEvent(
    key: "BattleCreated"
  ): TypedContractEvent<
    BattleCreatedEvent.InputTuple,
    BattleCreatedEvent.OutputTuple,
    BattleCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ChallengeTimeoutUpdated"
  ): TypedContractEvent<
    ChallengeTimeoutUpdatedEvent.InputTuple,
    ChallengeTimeoutUpdatedEvent.OutputTuple,
    ChallengeTimeoutUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ExpRewardsUpdated"
  ): TypedContractEvent<
    ExpRewardsUpdatedEvent.InputTuple,
    ExpRewardsUpdatedEvent.OutputTuple,
    ExpRewardsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BattleAccepted(uint256,address,uint256)": TypedContractEvent<
      BattleAcceptedEvent.InputTuple,
      BattleAcceptedEvent.OutputTuple,
      BattleAcceptedEvent.OutputObject
    >;
    BattleAccepted: TypedContractEvent<
      BattleAcceptedEvent.InputTuple,
      BattleAcceptedEvent.OutputTuple,
      BattleAcceptedEvent.OutputObject
    >;

    "BattleCancelled(uint256)": TypedContractEvent<
      BattleCancelledEvent.InputTuple,
      BattleCancelledEvent.OutputTuple,
      BattleCancelledEvent.OutputObject
    >;
    BattleCancelled: TypedContractEvent<
      BattleCancelledEvent.InputTuple,
      BattleCancelledEvent.OutputTuple,
      BattleCancelledEvent.OutputObject
    >;

    "BattleCompleted(uint256,address,uint256)": TypedContractEvent<
      BattleCompletedEvent.InputTuple,
      BattleCompletedEvent.OutputTuple,
      BattleCompletedEvent.OutputObject
    >;
    BattleCompleted: TypedContractEvent<
      BattleCompletedEvent.InputTuple,
      BattleCompletedEvent.OutputTuple,
      BattleCompletedEvent.OutputObject
    >;

    "BattleCreated(uint256,address,address,uint256)": TypedContractEvent<
      BattleCreatedEvent.InputTuple,
      BattleCreatedEvent.OutputTuple,
      BattleCreatedEvent.OutputObject
    >;
    BattleCreated: TypedContractEvent<
      BattleCreatedEvent.InputTuple,
      BattleCreatedEvent.OutputTuple,
      BattleCreatedEvent.OutputObject
    >;

    "ChallengeTimeoutUpdated(uint256,uint256)": TypedContractEvent<
      ChallengeTimeoutUpdatedEvent.InputTuple,
      ChallengeTimeoutUpdatedEvent.OutputTuple,
      ChallengeTimeoutUpdatedEvent.OutputObject
    >;
    ChallengeTimeoutUpdated: TypedContractEvent<
      ChallengeTimeoutUpdatedEvent.InputTuple,
      ChallengeTimeoutUpdatedEvent.OutputTuple,
      ChallengeTimeoutUpdatedEvent.OutputObject
    >;

    "ExpRewardsUpdated(uint32,uint32)": TypedContractEvent<
      ExpRewardsUpdatedEvent.InputTuple,
      ExpRewardsUpdatedEvent.OutputTuple,
      ExpRewardsUpdatedEvent.OutputObject
    >;
    ExpRewardsUpdated: TypedContractEvent<
      ExpRewardsUpdatedEvent.InputTuple,
      ExpRewardsUpdatedEvent.OutputTuple,
      ExpRewardsUpdatedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
