/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as test from "./test";
export type { test };
export type { BattleArena } from "./BattleArena";
export type { CardPack } from "./CardPack";
export type { PokeDEXCard } from "./PokeDEXCard";
