/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace VRFV2PlusClient {
  export type RandomWordsRequestStruct = {
    keyHash: BytesLike;
    subId: BigNumberish;
    requestConfirmations: BigNumberish;
    callbackGasLimit: BigNumberish;
    numWords: BigNumberish;
    extraArgs: BytesLike;
  };

  export type RandomWordsRequestStructOutput = [
    keyHash: string,
    subId: bigint,
    requestConfirmations: bigint,
    callbackGasLimit: bigint,
    numWords: bigint,
    extraArgs: string
  ] & {
    keyHash: string;
    subId: bigint;
    requestConfirmations: bigint;
    callbackGasLimit: bigint;
    numWords: bigint;
    extraArgs: string;
  };
}

export interface MockVRFCoordinatorV2PlusInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "fulfillRandomWords"
      | "fulfillRandomWordsWithSeed"
      | "getCurrentRequestId"
      | "getRequest"
      | "requestRandomWords"
      | "requestToConsumer"
      | "requestToNumWords"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "RandomWordsFulfilled" | "RandomWordsRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "fulfillRandomWords",
    values: [BigNumberish, AddressLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "fulfillRandomWordsWithSeed",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentRequestId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRandomWords",
    values: [VRFV2PlusClient.RandomWordsRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "requestToConsumer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestToNumWords",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "fulfillRandomWords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fulfillRandomWordsWithSeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentRequestId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRequest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestRandomWords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestToConsumer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestToNumWords",
    data: BytesLike
  ): Result;
}

export namespace RandomWordsFulfilledEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    outputSeed: BigNumberish,
    payment: BigNumberish,
    success: boolean
  ];
  export type OutputTuple = [
    requestId: bigint,
    outputSeed: bigint,
    payment: bigint,
    success: boolean
  ];
  export interface OutputObject {
    requestId: bigint;
    outputSeed: bigint;
    payment: bigint;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RandomWordsRequestedEvent {
  export type InputTuple = [
    keyHash: BytesLike,
    requestId: BigNumberish,
    preSeed: BigNumberish,
    subId: BigNumberish,
    minimumRequestConfirmations: BigNumberish,
    callbackGasLimit: BigNumberish,
    numWords: BigNumberish,
    extraArgs: BytesLike,
    sender: AddressLike
  ];
  export type OutputTuple = [
    keyHash: string,
    requestId: bigint,
    preSeed: bigint,
    subId: bigint,
    minimumRequestConfirmations: bigint,
    callbackGasLimit: bigint,
    numWords: bigint,
    extraArgs: string,
    sender: string
  ];
  export interface OutputObject {
    keyHash: string;
    requestId: bigint;
    preSeed: bigint;
    subId: bigint;
    minimumRequestConfirmations: bigint;
    callbackGasLimit: bigint;
    numWords: bigint;
    extraArgs: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockVRFCoordinatorV2Plus extends BaseContract {
  connect(runner?: ContractRunner | null): MockVRFCoordinatorV2Plus;
  waitForDeployment(): Promise<this>;

  interface: MockVRFCoordinatorV2PlusInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  fulfillRandomWords: TypedContractMethod<
    [
      requestId: BigNumberish,
      consumer: AddressLike,
      randomWords: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  fulfillRandomWordsWithSeed: TypedContractMethod<
    [requestId: BigNumberish, seed: BigNumberish],
    [void],
    "nonpayable"
  >;

  getCurrentRequestId: TypedContractMethod<[], [bigint], "view">;

  getRequest: TypedContractMethod<
    [requestId: BigNumberish],
    [[string, bigint] & { consumer: string; numWords: bigint }],
    "view"
  >;

  requestRandomWords: TypedContractMethod<
    [req: VRFV2PlusClient.RandomWordsRequestStruct],
    [bigint],
    "nonpayable"
  >;

  requestToConsumer: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  requestToNumWords: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "fulfillRandomWords"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      consumer: AddressLike,
      randomWords: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fulfillRandomWordsWithSeed"
  ): TypedContractMethod<
    [requestId: BigNumberish, seed: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCurrentRequestId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [[string, bigint] & { consumer: string; numWords: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "requestRandomWords"
  ): TypedContractMethod<
    [req: VRFV2PlusClient.RandomWordsRequestStruct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestToConsumer"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "requestToNumWords"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getEvent(
    key: "RandomWordsFulfilled"
  ): TypedContractEvent<
    RandomWordsFulfilledEvent.InputTuple,
    RandomWordsFulfilledEvent.OutputTuple,
    RandomWordsFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "RandomWordsRequested"
  ): TypedContractEvent<
    RandomWordsRequestedEvent.InputTuple,
    RandomWordsRequestedEvent.OutputTuple,
    RandomWordsRequestedEvent.OutputObject
  >;

  filters: {
    "RandomWordsFulfilled(uint256,uint256,uint96,bool)": TypedContractEvent<
      RandomWordsFulfilledEvent.InputTuple,
      RandomWordsFulfilledEvent.OutputTuple,
      RandomWordsFulfilledEvent.OutputObject
    >;
    RandomWordsFulfilled: TypedContractEvent<
      RandomWordsFulfilledEvent.InputTuple,
      RandomWordsFulfilledEvent.OutputTuple,
      RandomWordsFulfilledEvent.OutputObject
    >;

    "RandomWordsRequested(bytes32,uint256,uint256,uint256,uint16,uint32,uint32,bytes,address)": TypedContractEvent<
      RandomWordsRequestedEvent.InputTuple,
      RandomWordsRequestedEvent.OutputTuple,
      RandomWordsRequestedEvent.OutputObject
    >;
    RandomWordsRequested: TypedContractEvent<
      RandomWordsRequestedEvent.InputTuple,
      RandomWordsRequestedEvent.OutputTuple,
      RandomWordsRequestedEvent.OutputObject
    >;
  };
}
