/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IBattleArena {
  export type BattleStruct = {
    challenger: AddressLike;
    createdAt: BigNumberish;
    status: BigNumberish;
    opponent: AddressLike;
    completedAt: BigNumberish;
    challengerCardId: BigNumberish;
    winner: AddressLike;
    opponentCardId: BigNumberish;
    battleId: BigNumberish;
  };

  export type BattleStructOutput = [
    challenger: string,
    createdAt: bigint,
    status: bigint,
    opponent: string,
    completedAt: bigint,
    challengerCardId: bigint,
    winner: string,
    opponentCardId: bigint,
    battleId: bigint
  ] & {
    challenger: string;
    createdAt: bigint;
    status: bigint;
    opponent: string;
    completedAt: bigint;
    challengerCardId: bigint;
    winner: string;
    opponentCardId: bigint;
    battleId: bigint;
  };

  export type PlayerStatsStruct = {
    wins: BigNumberish;
    losses: BigNumberish;
    totalBattles: BigNumberish;
    currentStreak: BigNumberish;
    bestStreak: BigNumberish;
  };

  export type PlayerStatsStructOutput = [
    wins: bigint,
    losses: bigint,
    totalBattles: bigint,
    currentStreak: bigint,
    bestStreak: bigint
  ] & {
    wins: bigint;
    losses: bigint;
    totalBattles: bigint;
    currentStreak: bigint;
    bestStreak: bigint;
  };
}

export interface IBattleArenaInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptChallenge"
      | "cancelChallenge"
      | "createChallenge"
      | "getBattle"
      | "getLeaderboard"
      | "getPlayerStats"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BattleAccepted"
      | "BattleCancelled"
      | "BattleCompleted"
      | "BattleCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptChallenge",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelChallenge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createChallenge",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBattle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLeaderboard",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerStats",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBattle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLeaderboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerStats",
    data: BytesLike
  ): Result;
}

export namespace BattleAcceptedEvent {
  export type InputTuple = [
    battleId: BigNumberish,
    opponent: AddressLike,
    opponentCardId: BigNumberish
  ];
  export type OutputTuple = [
    battleId: bigint,
    opponent: string,
    opponentCardId: bigint
  ];
  export interface OutputObject {
    battleId: bigint;
    opponent: string;
    opponentCardId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BattleCancelledEvent {
  export type InputTuple = [battleId: BigNumberish];
  export type OutputTuple = [battleId: bigint];
  export interface OutputObject {
    battleId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BattleCompletedEvent {
  export type InputTuple = [
    battleId: BigNumberish,
    winner: AddressLike,
    winnerCardId: BigNumberish
  ];
  export type OutputTuple = [
    battleId: bigint,
    winner: string,
    winnerCardId: bigint
  ];
  export interface OutputObject {
    battleId: bigint;
    winner: string;
    winnerCardId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BattleCreatedEvent {
  export type InputTuple = [
    battleId: BigNumberish,
    challenger: AddressLike,
    opponent: AddressLike,
    challengerCardId: BigNumberish
  ];
  export type OutputTuple = [
    battleId: bigint,
    challenger: string,
    opponent: string,
    challengerCardId: bigint
  ];
  export interface OutputObject {
    battleId: bigint;
    challenger: string;
    opponent: string;
    challengerCardId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IBattleArena extends BaseContract {
  connect(runner?: ContractRunner | null): IBattleArena;
  waitForDeployment(): Promise<this>;

  interface: IBattleArenaInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptChallenge: TypedContractMethod<
    [battleId: BigNumberish, cardId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelChallenge: TypedContractMethod<
    [battleId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createChallenge: TypedContractMethod<
    [opponent: AddressLike, cardId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getBattle: TypedContractMethod<
    [battleId: BigNumberish],
    [IBattleArena.BattleStructOutput],
    "view"
  >;

  getLeaderboard: TypedContractMethod<
    [limit: BigNumberish],
    [[string[], bigint[]]],
    "view"
  >;

  getPlayerStats: TypedContractMethod<
    [player: AddressLike],
    [IBattleArena.PlayerStatsStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptChallenge"
  ): TypedContractMethod<
    [battleId: BigNumberish, cardId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelChallenge"
  ): TypedContractMethod<[battleId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createChallenge"
  ): TypedContractMethod<
    [opponent: AddressLike, cardId: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBattle"
  ): TypedContractMethod<
    [battleId: BigNumberish],
    [IBattleArena.BattleStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLeaderboard"
  ): TypedContractMethod<[limit: BigNumberish], [[string[], bigint[]]], "view">;
  getFunction(
    nameOrSignature: "getPlayerStats"
  ): TypedContractMethod<
    [player: AddressLike],
    [IBattleArena.PlayerStatsStructOutput],
    "view"
  >;

  getEvent(
    key: "BattleAccepted"
  ): TypedContractEvent<
    BattleAcceptedEvent.InputTuple,
    BattleAcceptedEvent.OutputTuple,
    BattleAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "BattleCancelled"
  ): TypedContractEvent<
    BattleCancelledEvent.InputTuple,
    BattleCancelledEvent.OutputTuple,
    BattleCancelledEvent.OutputObject
  >;
  getEvent(
    key: "BattleCompleted"
  ): TypedContractEvent<
    BattleCompletedEvent.InputTuple,
    BattleCompletedEvent.OutputTuple,
    BattleCompletedEvent.OutputObject
  >;
  getEvent(
    key: "BattleCreated"
  ): TypedContractEvent<
    BattleCreatedEvent.InputTuple,
    BattleCreatedEvent.OutputTuple,
    BattleCreatedEvent.OutputObject
  >;

  filters: {
    "BattleAccepted(uint256,address,uint256)": TypedContractEvent<
      BattleAcceptedEvent.InputTuple,
      BattleAcceptedEvent.OutputTuple,
      BattleAcceptedEvent.OutputObject
    >;
    BattleAccepted: TypedContractEvent<
      BattleAcceptedEvent.InputTuple,
      BattleAcceptedEvent.OutputTuple,
      BattleAcceptedEvent.OutputObject
    >;

    "BattleCancelled(uint256)": TypedContractEvent<
      BattleCancelledEvent.InputTuple,
      BattleCancelledEvent.OutputTuple,
      BattleCancelledEvent.OutputObject
    >;
    BattleCancelled: TypedContractEvent<
      BattleCancelledEvent.InputTuple,
      BattleCancelledEvent.OutputTuple,
      BattleCancelledEvent.OutputObject
    >;

    "BattleCompleted(uint256,address,uint256)": TypedContractEvent<
      BattleCompletedEvent.InputTuple,
      BattleCompletedEvent.OutputTuple,
      BattleCompletedEvent.OutputObject
    >;
    BattleCompleted: TypedContractEvent<
      BattleCompletedEvent.InputTuple,
      BattleCompletedEvent.OutputTuple,
      BattleCompletedEvent.OutputObject
    >;

    "BattleCreated(uint256,address,address,uint256)": TypedContractEvent<
      BattleCreatedEvent.InputTuple,
      BattleCreatedEvent.OutputTuple,
      BattleCreatedEvent.OutputObject
    >;
    BattleCreated: TypedContractEvent<
      BattleCreatedEvent.InputTuple,
      BattleCreatedEvent.OutputTuple,
      BattleCreatedEvent.OutputObject
    >;
  };
}
