/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ICardPack {
  export type PackRequestStruct = {
    buyer: AddressLike;
    packType: BigNumberish;
    requestId: BigNumberish;
    fulfilled: boolean;
    pendingIndex: BigNumberish;
    cardIds: BigNumberish[];
  };

  export type PackRequestStructOutput = [
    buyer: string,
    packType: bigint,
    requestId: bigint,
    fulfilled: boolean,
    pendingIndex: bigint,
    cardIds: bigint[]
  ] & {
    buyer: string;
    packType: bigint;
    requestId: bigint;
    fulfilled: boolean;
    pendingIndex: bigint;
    cardIds: bigint[];
  };
}

export interface ICardPackInterface extends Interface {
  getFunction(
    nameOrSignature: "getPackPrice" | "getPackRequest" | "purchasePack"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PackOpened" | "PackPurchased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getPackPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPackRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "purchasePack",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPackPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPackRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchasePack",
    data: BytesLike
  ): Result;
}

export namespace PackOpenedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    buyer: AddressLike,
    cardIds: BigNumberish[]
  ];
  export type OutputTuple = [
    requestId: bigint,
    buyer: string,
    cardIds: bigint[]
  ];
  export interface OutputObject {
    requestId: bigint;
    buyer: string;
    cardIds: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PackPurchasedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    buyer: AddressLike,
    packType: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    buyer: string,
    packType: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    buyer: string;
    packType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ICardPack extends BaseContract {
  connect(runner?: ContractRunner | null): ICardPack;
  waitForDeployment(): Promise<this>;

  interface: ICardPackInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPackPrice: TypedContractMethod<[packType: BigNumberish], [bigint], "view">;

  getPackRequest: TypedContractMethod<
    [requestId: BigNumberish],
    [ICardPack.PackRequestStructOutput],
    "view"
  >;

  purchasePack: TypedContractMethod<
    [packType: BigNumberish],
    [bigint],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPackPrice"
  ): TypedContractMethod<[packType: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPackRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [ICardPack.PackRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "purchasePack"
  ): TypedContractMethod<[packType: BigNumberish], [bigint], "payable">;

  getEvent(
    key: "PackOpened"
  ): TypedContractEvent<
    PackOpenedEvent.InputTuple,
    PackOpenedEvent.OutputTuple,
    PackOpenedEvent.OutputObject
  >;
  getEvent(
    key: "PackPurchased"
  ): TypedContractEvent<
    PackPurchasedEvent.InputTuple,
    PackPurchasedEvent.OutputTuple,
    PackPurchasedEvent.OutputObject
  >;

  filters: {
    "PackOpened(uint256,address,uint256[])": TypedContractEvent<
      PackOpenedEvent.InputTuple,
      PackOpenedEvent.OutputTuple,
      PackOpenedEvent.OutputObject
    >;
    PackOpened: TypedContractEvent<
      PackOpenedEvent.InputTuple,
      PackOpenedEvent.OutputTuple,
      PackOpenedEvent.OutputObject
    >;

    "PackPurchased(uint256,address,uint8)": TypedContractEvent<
      PackPurchasedEvent.InputTuple,
      PackPurchasedEvent.OutputTuple,
      PackPurchasedEvent.OutputObject
    >;
    PackPurchased: TypedContractEvent<
      PackPurchasedEvent.InputTuple,
      PackPurchasedEvent.OutputTuple,
      PackPurchasedEvent.OutputObject
    >;
  };
}
