/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBattleArena } from "./IBattleArena";
export type { ICardPack } from "./ICardPack";
export type { IPokeDEXCard } from "./IPokeDEXCard";
