/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IPokeDEXCard {
  export type CardStatsStruct = {
    hp: BigNumberish;
    attack: BigNumberish;
    defense: BigNumberish;
    speed: BigNumberish;
    pokemonType: BigNumberish;
    rarity: BigNumberish;
    generation: BigNumberish;
    experience: BigNumberish;
  };

  export type CardStatsStructOutput = [
    hp: bigint,
    attack: bigint,
    defense: bigint,
    speed: bigint,
    pokemonType: bigint,
    rarity: bigint,
    generation: bigint,
    experience: bigint
  ] & {
    hp: bigint;
    attack: bigint;
    defense: bigint;
    speed: bigint;
    pokemonType: bigint;
    rarity: bigint;
    generation: bigint;
    experience: bigint;
  };
}

export interface IPokeDEXCardInterface extends Interface {
  getFunction(
    nameOrSignature: "addExperience" | "getCardStats" | "mintCard"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CardMinted" | "CardStatsUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addExperience",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCardStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintCard",
    values: [AddressLike, string, IPokeDEXCard.CardStatsStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "addExperience",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCardStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintCard", data: BytesLike): Result;
}

export namespace CardMintedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    owner: AddressLike,
    pokemonType: BigNumberish,
    rarity: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    owner: string,
    pokemonType: bigint,
    rarity: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    owner: string;
    pokemonType: bigint;
    rarity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CardStatsUpdatedEvent {
  export type InputTuple = [tokenId: BigNumberish, newExperience: BigNumberish];
  export type OutputTuple = [tokenId: bigint, newExperience: bigint];
  export interface OutputObject {
    tokenId: bigint;
    newExperience: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPokeDEXCard extends BaseContract {
  connect(runner?: ContractRunner | null): IPokeDEXCard;
  waitForDeployment(): Promise<this>;

  interface: IPokeDEXCardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addExperience: TypedContractMethod<
    [tokenId: BigNumberish, expAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getCardStats: TypedContractMethod<
    [tokenId: BigNumberish],
    [IPokeDEXCard.CardStatsStructOutput],
    "view"
  >;

  mintCard: TypedContractMethod<
    [to: AddressLike, tokenURI: string, stats: IPokeDEXCard.CardStatsStruct],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addExperience"
  ): TypedContractMethod<
    [tokenId: BigNumberish, expAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCardStats"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [IPokeDEXCard.CardStatsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintCard"
  ): TypedContractMethod<
    [to: AddressLike, tokenURI: string, stats: IPokeDEXCard.CardStatsStruct],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "CardMinted"
  ): TypedContractEvent<
    CardMintedEvent.InputTuple,
    CardMintedEvent.OutputTuple,
    CardMintedEvent.OutputObject
  >;
  getEvent(
    key: "CardStatsUpdated"
  ): TypedContractEvent<
    CardStatsUpdatedEvent.InputTuple,
    CardStatsUpdatedEvent.OutputTuple,
    CardStatsUpdatedEvent.OutputObject
  >;

  filters: {
    "CardMinted(uint256,address,uint8,uint8)": TypedContractEvent<
      CardMintedEvent.InputTuple,
      CardMintedEvent.OutputTuple,
      CardMintedEvent.OutputObject
    >;
    CardMinted: TypedContractEvent<
      CardMintedEvent.InputTuple,
      CardMintedEvent.OutputTuple,
      CardMintedEvent.OutputObject
    >;

    "CardStatsUpdated(uint256,uint32)": TypedContractEvent<
      CardStatsUpdatedEvent.InputTuple,
      CardStatsUpdatedEvent.OutputTuple,
      CardStatsUpdatedEvent.OutputObject
    >;
    CardStatsUpdated: TypedContractEvent<
      CardStatsUpdatedEvent.InputTuple,
      CardStatsUpdatedEvent.OutputTuple,
      CardStatsUpdatedEvent.OutputObject
    >;
  };
}
