/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBattleArena,
  IBattleArenaInterface,
} from "../../../contracts/interfaces/IBattleArena";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "battleId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "opponent",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "opponentCardId",
        type: "uint256",
      },
    ],
    name: "BattleAccepted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "battleId",
        type: "uint256",
      },
    ],
    name: "BattleCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "battleId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "winner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "winnerCardId",
        type: "uint256",
      },
    ],
    name: "BattleCompleted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "battleId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "challenger",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "opponent",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "challengerCardId",
        type: "uint256",
      },
    ],
    name: "BattleCreated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "battleId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "cardId",
        type: "uint256",
      },
    ],
    name: "acceptChallenge",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "battleId",
        type: "uint256",
      },
    ],
    name: "cancelChallenge",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "opponent",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "cardId",
        type: "uint256",
      },
    ],
    name: "createChallenge",
    outputs: [
      {
        internalType: "uint256",
        name: "battleId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "battleId",
        type: "uint256",
      },
    ],
    name: "getBattle",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "challenger",
            type: "address",
          },
          {
            internalType: "uint48",
            name: "createdAt",
            type: "uint48",
          },
          {
            internalType: "enum IBattleArena.BattleStatus",
            name: "status",
            type: "uint8",
          },
          {
            internalType: "address",
            name: "opponent",
            type: "address",
          },
          {
            internalType: "uint48",
            name: "completedAt",
            type: "uint48",
          },
          {
            internalType: "uint48",
            name: "challengerCardId",
            type: "uint48",
          },
          {
            internalType: "address",
            name: "winner",
            type: "address",
          },
          {
            internalType: "uint48",
            name: "opponentCardId",
            type: "uint48",
          },
          {
            internalType: "uint256",
            name: "battleId",
            type: "uint256",
          },
        ],
        internalType: "struct IBattleArena.Battle",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "limit",
        type: "uint256",
      },
    ],
    name: "getLeaderboard",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "player",
        type: "address",
      },
    ],
    name: "getPlayerStats",
    outputs: [
      {
        components: [
          {
            internalType: "uint64",
            name: "wins",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "losses",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "totalBattles",
            type: "uint64",
          },
          {
            internalType: "uint32",
            name: "currentStreak",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "bestStreak",
            type: "uint32",
          },
        ],
        internalType: "struct IBattleArena.PlayerStats",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IBattleArena__factory {
  static readonly abi = _abi;
  static createInterface(): IBattleArenaInterface {
    return new Interface(_abi) as IBattleArenaInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBattleArena {
    return new Contract(address, _abi, runner) as unknown as IBattleArena;
  }
}
