/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICardPack,
  ICardPackInterface,
} from "../../../contracts/interfaces/ICardPack";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "buyer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "cardIds",
        type: "uint256[]",
      },
    ],
    name: "PackOpened",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "buyer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "enum ICardPack.PackType",
        name: "packType",
        type: "uint8",
      },
    ],
    name: "PackPurchased",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "enum ICardPack.PackType",
        name: "packType",
        type: "uint8",
      },
    ],
    name: "getPackPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
    ],
    name: "getPackRequest",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "buyer",
            type: "address",
          },
          {
            internalType: "enum ICardPack.PackType",
            name: "packType",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "requestId",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "fulfilled",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "pendingIndex",
            type: "uint256",
          },
          {
            internalType: "uint256[]",
            name: "cardIds",
            type: "uint256[]",
          },
        ],
        internalType: "struct ICardPack.PackRequest",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum ICardPack.PackType",
        name: "packType",
        type: "uint8",
      },
    ],
    name: "purchasePack",
    outputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class ICardPack__factory {
  static readonly abi = _abi;
  static createInterface(): ICardPackInterface {
    return new Interface(_abi) as ICardPackInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ICardPack {
    return new Contract(address, _abi, runner) as unknown as ICardPack;
  }
}
