/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBattleArena__factory } from "./IBattleArena__factory";
export { ICardPack__factory } from "./ICardPack__factory";
export { IPokeDEXCard__factory } from "./IPokeDEXCard__factory";
