/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPokeDEXCard,
  IPokeDEXCardInterface,
} from "../../../contracts/interfaces/IPokeDEXCard";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "enum IPokeDEXCard.PokemonType",
        name: "pokemonType",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "enum IPokeDEXCard.Rarity",
        name: "rarity",
        type: "uint8",
      },
    ],
    name: "CardMinted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "newExperience",
        type: "uint32",
      },
    ],
    name: "CardStatsUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "expAmount",
        type: "uint32",
      },
    ],
    name: "addExperience",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "getCardStats",
    outputs: [
      {
        components: [
          {
            internalType: "uint16",
            name: "hp",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "attack",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "defense",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "speed",
            type: "uint16",
          },
          {
            internalType: "enum IPokeDEXCard.PokemonType",
            name: "pokemonType",
            type: "uint8",
          },
          {
            internalType: "enum IPokeDEXCard.Rarity",
            name: "rarity",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "generation",
            type: "uint8",
          },
          {
            internalType: "uint32",
            name: "experience",
            type: "uint32",
          },
        ],
        internalType: "struct IPokeDEXCard.CardStats",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "string",
        name: "tokenURI",
        type: "string",
      },
      {
        components: [
          {
            internalType: "uint16",
            name: "hp",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "attack",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "defense",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "speed",
            type: "uint16",
          },
          {
            internalType: "enum IPokeDEXCard.PokemonType",
            name: "pokemonType",
            type: "uint8",
          },
          {
            internalType: "enum IPokeDEXCard.Rarity",
            name: "rarity",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "generation",
            type: "uint8",
          },
          {
            internalType: "uint32",
            name: "experience",
            type: "uint32",
          },
        ],
        internalType: "struct IPokeDEXCard.CardStats",
        name: "stats",
        type: "tuple",
      },
    ],
    name: "mintCard",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPokeDEXCard__factory {
  static readonly abi = _abi;
  static createInterface(): IPokeDEXCardInterface {
    return new Interface(_abi) as IPokeDEXCardInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPokeDEXCard {
    return new Contract(address, _abi, runner) as unknown as IPokeDEXCard;
  }
}
