// =============================================================================
// ABI DEI CONTRATTI SMART - Interfacce per comunicare con la blockchain
// SMART CONTRACT ABIs - Interfaces for communicating with the blockchain
//
// COS'E' UN ABI?
// ABI sta per "Application Binary Interface". E' la specifica che descrive
// quali funzioni uno smart contract espone e come chiamarle. Quando il bot
// vuole leggere dati dalla blockchain o inviare una transazione, ha bisogno
// dell'ABI per sapere come "parlare" con il contratto.
//
// Pensalo come un menu di un ristorante: senza il menu (ABI) non sai
// cosa puoi ordinare (quali funzioni puoi chiamare) ne' come ordinarlo
// (quali parametri servono).
//
// WHAT IS AN ABI?
// ABI stands for "Application Binary Interface". It's the specification
// that describes which functions a smart contract exposes and how to call
// them. When the bot wants to read data from the blockchain or send a
// transaction, it needs the ABI to know how to "talk" to the contract.
//
// Think of it like a restaurant menu: without the menu (ABI), you don't
// know what you can order (which functions you can call) or how to order
// it (which parameters are needed).
//
// FORMATO HUMAN-READABLE / HUMAN-READABLE FORMAT
// Ethers.js supporta due formati di ABI: il JSON completo (generato dal
// compilatore Solidity) e il formato "human-readable" usato qui, che e'
// piu' conciso e leggibile. Ogni stringa descrive una singola funzione
// o evento del contratto.
//
// Ethers.js supports two ABI formats: the full JSON (generated by the
// Solidity compiler) and the "human-readable" format used here, which
// is more concise and readable. Each string describes a single function
// or event of the contract.
//
// TIPI DI FUNZIONI / FUNCTION TYPES
// - "view": Funzione di sola lettura, non costa gas (gratuita).
//           Read-only function, costs no gas (free).
// - "payable": Funzione che accetta ETH insieme alla chiamata.
//              Function that accepts ETH along with the call.
// - (senza modificatore): Funzione di scrittura che modifica lo stato.
//   (no modifier): Write function that modifies the state.
//
// SOLO I CONTRATTI ATTIVI SONO INCLUSI
// Questo file include solo le ABI dei contratti CustomCards e Marketplace,
// che sono gli unici contratti con cui il bot interagisce direttamente.
//
// ONLY ACTIVE CONTRACTS ARE INCLUDED
// This file includes only the ABIs for CustomCards and Marketplace,
// which are the only contracts the bot interacts with directly.
// =============================================================================

// =============================================================================
// ABI DEL CONTRATTO CUSTOM CARDS (PokeDEXCustomCards.sol)
// CUSTOM CARDS CONTRACT ABI (PokeDEXCustomCards.sol)
//
// Questo contratto ERC-721 gestisce le carte Pokemon personalizzate.
// Permette agli utenti di creare ("mintare") nuove carte con statistiche
// personalizzate, immagini e metadati salvati su IPFS. Ogni carta e' un
// NFT unico identificato da un tokenId.
//
// This ERC-721 contract manages custom Pokemon cards. It allows users
// to create ("mint") new cards with custom stats, images and metadata
// saved on IPFS. Each card is a unique NFT identified by a tokenId.
// =============================================================================

export const CUSTOM_CARDS_ABI = [
  // ---------------------------------------------------------------------------
  // FUNZIONI DI LETTURA (view) - Gratuite, non richiedono gas
  // READ FUNCTIONS (view) - Free, no gas required
  // ---------------------------------------------------------------------------

  // Restituisce il numero di carte possedute da un indirizzo
  // Returns the number of cards owned by an address
  "function balanceOf(address owner) view returns (uint256)",

  // Restituisce l'indirizzo del proprietario di una carta specifica
  // Returns the owner's address for a specific card
  "function ownerOf(uint256 tokenId) view returns (address)",

  // Restituisce il numero totale di carte create (mintate) nel contratto
  // Returns the total number of cards created (minted) in the contract
  "function totalSupply() view returns (uint256)",

  // Restituisce la tariffa in wei richiesta per mintare una nuova carta
  // Returns the fee in wei required to mint a new card
  "function mintingFee() view returns (uint256)",

  // Restituisce l'URI dei metadati di una carta (link IPFS con nome, desc, immagine)
  // Returns a card's metadata URI (IPFS link with name, description, image)
  "function tokenURI(uint256 tokenId) view returns (string)",

  // Restituisce tutte le statistiche di una carta: HP, attacco, difesa, velocita',
  // tipo, rarita', indirizzo del creatore, data di creazione, stato di verifica.
  // La risposta e' una struct Solidity (tuple) che ethers.js converte in un oggetto.
  //
  // Returns all stats for a card: HP, attack, defense, speed, type, rarity,
  // creator's address, creation date, verification status.
  // The response is a Solidity struct (tuple) that ethers.js converts to an object.
  "function getCardStats(uint256 tokenId) view returns (tuple(uint16 hp, uint16 attack, uint16 defense, uint16 speed, uint8 cardType, uint8 rarity, address creator, uint256 createdAt, bool verified))",

  // Restituisce tutti i tokenId posseduti da un indirizzo (utile per mostrare la collezione)
  // Returns all tokenIds owned by an address (useful for showing the collection)
  "function tokensOfOwner(address owner) view returns (uint256[])",

  // Restituisce tutti i tokenId creati da un indirizzo (carte di cui e' l'autore)
  // Returns all tokenIds created by an address (cards they authored)
  "function getCreatorCards(address creator) view returns (uint256[])",

  // Verifica se una carta e' stata bannata (rimossa per violazione regole)
  // Checks if a card has been banned (removed for rule violations)
  "function isBanned(uint256 tokenId) view returns (bool)",

  // Calcola il "battle power" di una carta (usato per il sistema di combattimento)
  // Calculates a card's "battle power" (used for the battle system)
  "function calculateBattlePower(uint256 tokenId) view returns (uint256)",

  // ---------------------------------------------------------------------------
  // FUNZIONI DI SCRITTURA - Richiedono gas e firma della transazione
  // WRITE FUNCTIONS - Require gas and transaction signing
  // ---------------------------------------------------------------------------

  // Crea (minta) una nuova carta NFT. Parametri:
  //   metadataURI: link IPFS ai metadati JSON della carta
  //   hp, attack, defense, speed: statistiche della carta (uint16, 0-65535)
  //   cardType: tipo Pokemon (uint8, 0-17)
  //   rarity: livello di rarita' (uint8, 0-4)
  //   royaltyPercentage: percentuale di royalty per il creatore sulle rivendite (uint96)
  // "payable" significa che bisogna inviare ETH (la mintingFee) insieme alla chiamata.
  //
  // Creates (mints) a new NFT card. Parameters:
  //   metadataURI: IPFS link to the card's JSON metadata
  //   hp, attack, defense, speed: card stats (uint16, 0-65535)
  //   cardType: Pokemon type (uint8, 0-17)
  //   rarity: rarity tier (uint8, 0-4)
  //   royaltyPercentage: creator's royalty percentage on resales (uint96)
  // "payable" means ETH (the mintingFee) must be sent along with the call.
  "function createCard(string metadataURI, uint16 hp, uint16 attack, uint16 defense, uint16 speed, uint8 cardType, uint8 rarity, uint96 royaltyPercentage) payable returns (uint256)"
];

// =============================================================================
// ABI DEL CONTRATTO MARKETPLACE (PokeDEXMarketplace.sol)
// MARKETPLACE CONTRACT ABI (PokeDEXMarketplace.sol)
//
// Questo contratto gestisce la compravendita di carte NFT tra utenti.
// Supporta due meccanismi di vendita:
// 1. Listing a prezzo fisso: il venditore fissa un prezzo, il compratore paga.
// 2. Offerte: un compratore propone un prezzo, il venditore puo' accettare.
//
// This contract manages buying and selling NFT cards between users.
// It supports two sale mechanisms:
// 1. Fixed-price listing: the seller sets a price, the buyer pays it.
// 2. Offers: a buyer proposes a price, the seller can accept.
// =============================================================================

export const MARKETPLACE_ABI = [
  // ---------------------------------------------------------------------------
  // FUNZIONI DI LETTURA (view) - Gratuite, non richiedono gas
  // READ FUNCTIONS (view) - Free, no gas required
  // ---------------------------------------------------------------------------

  // Restituisce la percentuale di commissione del marketplace (es. 250 = 2.5%)
  // Returns the marketplace fee percentage (e.g. 250 = 2.5%)
  "function marketplaceFee() view returns (uint256)",

  // Restituisce tutti i dettagli di un listing specifico: venditore, contratto NFT,
  // tokenId, prezzo, stato attivo, data creazione.
  //
  // Returns all details of a specific listing: seller, NFT contract,
  // tokenId, price, active status, creation date.
  //
  // NOTA: Il contratto deployato NON include il campo imageURI nella struct Listing.
  // Il codice sorgente Solidity puo' differire — questa ABI riflette il contratto REALE.
  //
  // NOTE: The deployed contract does NOT include the imageURI field in the Listing struct.
  // The Solidity source may differ — this ABI reflects the ACTUAL deployed contract.
  "function getListing(uint256 listingId) view returns (tuple(address seller, address nftContract, uint256 tokenId, uint256 price, bool active, uint256 createdAt))",

  // Restituisce tutti i dettagli di un'offerta: compratore, contratto NFT,
  // tokenId, importo offerto, scadenza e stato attivo.
  //
  // Returns all details of an offer: buyer, NFT contract,
  // tokenId, offered amount, expiration and active status.
  "function getOffer(uint256 offerId) view returns (tuple(address buyer, address nftContract, uint256 tokenId, uint256 amount, uint256 expiresAt, bool active))",

  // Restituisce tutti gli ID dei listing creati da un venditore
  // Returns all listing IDs created by a seller
  "function getSellerListings(address seller) view returns (uint256[])",

  // Restituisce tutti gli ID delle offerte fatte da un compratore
  // Returns all offer IDs made by a buyer
  "function getBuyerOffers(address buyer) view returns (uint256[])",

  // NOTA: totalListings() NON esiste nel contratto deployato.
  // Il bot usa getSellerListings() e la scansione diretta degli ID.
  //
  // NOTE: totalListings() does NOT exist in the deployed contract.
  // The bot uses getSellerListings() and direct ID scanning instead.

  // ---------------------------------------------------------------------------
  // FUNZIONI DI SCRITTURA - Richiedono gas e firma della transazione
  // WRITE FUNCTIONS - Require gas and transaction signing
  // ---------------------------------------------------------------------------

  // Mette in vendita una carta NFT. Richiede che il marketplace abbia l'approvazione
  // per trasferire il token (tramite approve/setApprovalForAll sul contratto NFT).
  //
  // Lists an NFT card for sale. Requires the marketplace to have approval
  // to transfer the token (via approve/setApprovalForAll on the NFT contract).
  // NOTA: Il contratto deployato usa la firma a 3 parametri (senza imageURI).
  // NOTE: The deployed contract uses the 3-parameter signature (without imageURI).
  "function listNFT(address nftContract, uint256 tokenId, uint256 price) returns (uint256)",

  // Acquista una carta listata. "payable" perche' bisogna inviare il prezzo in ETH.
  // expectedPrice previene il front-running (se il prezzo cambia, la tx fallisce).
  //
  // Buys a listed card. "payable" because the price must be sent in ETH.
  // expectedPrice prevents front-running (if price changes, the tx fails).
  "function buyNFT(uint256 listingId, uint256 expectedPrice) payable",

  // Cancella un listing attivo (solo il venditore puo' farlo)
  // Cancels an active listing (only the seller can do this)
  "function cancelListing(uint256 listingId)",

  // Fa un'offerta per un NFT specifico. "payable" perche' l'importo dell'offerta
  // viene inviato e tenuto in escrow nel contratto fino ad accettazione o cancellazione.
  //
  // Makes an offer for a specific NFT. "payable" because the offer amount
  // is sent and held in escrow in the contract until acceptance or cancellation.
  "function makeOffer(address nftContract, uint256 tokenId, uint256 expiresIn) payable returns (uint256)",

  // Accetta un'offerta ricevuta (solo il proprietario dell'NFT puo' farlo)
  // Accepts a received offer (only the NFT owner can do this)
  "function acceptOffer(uint256 offerId)",

  // Cancella un'offerta fatta (solo chi ha fatto l'offerta puo' farlo).
  // L'importo in escrow viene restituito al compratore.
  //
  // Cancels a made offer (only the offer maker can do this).
  // The escrowed amount is returned to the buyer.
  "function cancelOffer(uint256 offerId)",

  // ---------------------------------------------------------------------------
  // EVENTI - Emessi dal contratto quando accadono azioni importanti
  // EVENTS - Emitted by the contract when important actions happen
  //
  // Gli eventi vengono salvati nei log della blockchain e possono essere
  // "ascoltati" dal bot per reagire in tempo reale (es. notificare un utente
  // quando la sua carta viene venduta). "indexed" permette di filtrare
  // gli eventi per quel campo specifico.
  //
  // Events are saved in blockchain logs and can be "listened to" by the
  // bot to react in real time (e.g. notify a user when their card is sold).
  // "indexed" allows filtering events by that specific field.
  // ---------------------------------------------------------------------------

  // Emesso quando una carta viene messa in vendita
  // Emitted when a card is listed for sale
  "event NFTListed(uint256 indexed listingId, address indexed seller, address indexed nftContract, uint256 tokenId, uint256 price)",

  // Emesso quando una carta viene acquistata
  // Emitted when a card is purchased
  "event NFTSold(uint256 indexed listingId, address indexed buyer, address indexed seller, uint256 price)"
];
